pub const CATEGORIES: &[(&str, &str)] = &[
    ("3d", "3D"),
    ("abstract", "Abstract"),
    ("amoled", "AMOLED"),
    ("animals", "Animals"),
    ("anime", "Anime"),
    ("architecture", "Architecture"),
    ("art", "Art"),
    ("black and white", "Black and White"),
    ("car", "Car"),
    ("cartoon", "Cartoon"),
    ("city", "City"),
    ("cyberpunk", "Cyberpunk"),
    ("dark theme", "Dark Theme"),
    ("fantasy", "Fantasy"),
    ("food", "Food"),
    ("gaming", "Gaming"),
    ("holiday", "Holiday"),
    ("landscape", "Landscape"),
    ("light theme", "Light Theme"),
    ("macro", "Macro"),
    ("minimal", "Minimal"),
    ("motorcycle", "Motorcycle"),
    ("mountains", "Mountains"),
    ("movies", "Movies"),
    ("music", "Music"),
    ("nature", "Nature"),
    ("neon", "Neon"),
    ("ocean", "Ocean"),
    ("pattern", "Pattern"),
    ("photography", "Photography"),
    ("portrait", "Portrait"),
    ("space", "Space"),
    ("sport", "Sport"),
    ("technology", "Technology"),
    ("texture", "Texture"),
    ("typography", "Typography"),
    ("vaporwave", "Vaporwave"),
    ("vehicles", "Vehicles"),
    ("vintage", "Vintage"),
];
